<?php

namespace Tigralt\EZRatingBundle\Repository;

/**
 * RatingThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingThreadRepository extends \Doctrine\ORM\EntityRepository
{
}
